# Generated by Django 2.1.5 on 2019-02-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190209_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='score',
            new_name='kills',
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
